version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: license_management_db
    environment:
      POSTGRES_DB: LicenseManagementDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LiebherrLicenseManagementTool123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: